### ISSUE TITLE
I use method 1 and how long should I wait for the next step?

### ISSUE THREAD

**Issue by bingbingwangyyds** [Niedzielan/aoe2_gpv_decrypt_py#1]
I use method 1 and how long should I wait in "wait a few minutes"? I have waited for an hour.If it has signal this step is finished?When I should take the next step "gpv_decrypt.py"?
Waiting for your answer.

**Comment by Niedzielan** [comment]
On my machine, the whole thing takes about 3 minutes. Unless you have an exceptionally old CPU it shouldn't take an hour.

What does the python output say?
It should be something like:
```
finding potential TEA-encrypted key-iv pair blocks
sorting potential TEA-encrypted key-iv pair blocks into potential keyblobs
finding potential TEA-keys
Gathering testing data
Testing key/iv / tea pairs against testing data
b'Base' keys found
b'DLC3' keys found
b'Pomp' keys found
b'DLC4' keys found
b'Phil' keys found
b'DLC1' keys found
b'DLC2' keys found
Outputting found keys to keys directory
```
The longest stage is `finding potential TEA-keys`, everything else should be fairly quick.
If it's completed, you should see keys and ivs in the keys folder, and can proceed.

The script currently doesn't create the folder if it doesn't exist - not an issue for the release but if you cloned the git repo that might cause issues. I'll look at fixing that, but for now just make sure you have `in`, `out`, and `keys` folders.

~~I've just tested it with the latest aoe2 version and it seems to have missed DLC1 and DLC2, so you'd probably be better off with Method 2 until I figure out what's gone wrong~~
as of update #118476, DLC1 and DLC2 have their TEA keys further apart than expected. In `bruteforce_keys.py` I suggest upping `TEA_IV_DIST_FROM_KEY_MAX` to `0x100` which is what I've done in 1.0.1

**Comment by bingbingwangyyds** [comment]
I use method 1 get struck in this words "Testing key/iv / tea pairs against testing data" for a long time.
I use method 2 to succeed to take all keys except the b'Phil' keys because I did not buy the non-civ DLC before.Ask a question about how to do the turning against like change the .aoe2capmaign to .aoe2campaign.gpv?It is very important for the custom designers to prevent their works from being stolen by others.

**Comment by Niedzielan** [comment]
Testing the keys is the 2nd longest part, but shouldn't take _too_ long unless you increased any of the constants at the top of the file (they make finding the keys take slightly longer and testing take _significantly_ longer). 
I made sure to load the test data so there shouldn't be excessive IO. Perhaps if you have low RAM there might be some slowdown if it's trying to use the pagefile.  
Doing some testing while I write this comment: if there is nothing in the `in` folder, it will take a very long time for `Testing key/iv / tea pairs against testing data` to complete, so make sure there are `.gpv` files in the `in` folder. I'll make sure to add a check for that in the next update.

I list the `gpv_decrypt.py` arguments in `Readme.txt` (or call `python gpv_decrypt.py -h`)
To encrypt .aoe2campaign to .aoe2campaign.gpv you can use the argument `-m MAGICHEADER`
The magic header can be any 4-bytes, but in practice there is no reason to specify a custom one - the game won't have the keys to decrypt it - just use Base, so you would call  `python gpv_decrypt.py -m Base`
Then, of course, specifying input and output. By default it will take all gpv files in `in` and output to `out`, you can change this with `-i` and `-o`
Additionally, `-a` will ignore the requirement for the input files to be .gpv
The simplest way to encrypt would be to put your custom campaign into `in`, and run `python gpv_decrypt.py -m Base -a`, then find your file in `out`

However, I've just tested and found that the game **cannot load gpv files as custom campaigns**. That does make sense, otherwise people could just copy the DLC as custom campaigns.

So I doubt this tool will be useful for any copy-protection.  
The only thing I haven't tested is replacing an official campaign with one of the same name but edited contents. It might work if there are no checksums, but anyone you share it with would have to install it manually.

**Comment by bingbingwangyyds** [comment]
If someone install a version there is all DLCs included but it is pirated version not he buy,whether he can take the V&V(all campaigns DLCs) .aoe2campaign.gpv documents into .aoe2campaign successfully?

**Comment by Niedzielan** [comment]
It is _possible_ to play unowned DLC by decrypting the .gpv files and copying the .aoe2campaign into the custom campaign folder. You cannot open a scenario in the scenario editor if it has a faction you do not own the DLC for.

There is no legal way to acquire the DLC .gpv files without purchasing the DLC. You cannot legally share any campaigns, decrypted or otherwise, without permission of the original copyright holder (i.e. you can't share decrypted DLC campaigns unless the AoE2 developers say you can).
This tool does not support piracy, though it cannot make any distinction between a legitimate copy of the game or a pirated one.

From a practical point of view - if you wanted to use this tool for piracy or circumventing copyright, there's little point. You would have to source a pirated version of the game or DLC in order to obtain the campaigns, at which point you would already have a playable version of the game or DLC. and thus have no _need_ to use this tool to attempt circumventing DRM.
