### ISSUE TITLE
Can't load decrypted gpv file?

### ISSUE THREAD

**Issue by KyuEnysomenm** [Niedzielan/aoe2_gpv_decrypt_py#3]
I used method2 and got one .iv file (no name), one .key file (no name), and one aoe2de.sbox file with CE using method 2. However, the aoe2campaign file after running gpv_decrypt.py can't be recognized in aoe2DE campaign editor. The one I chose was wecam1.

It seems the cam1.aoe2campaign can be recogonized, so I wonder how to get those files correctly with DE dlcs.

**Comment by Niedzielan** [comment]
For now, you should use the method 1 I just uploaded (I forgot to upload it for the earlier update where method 2 still worked). When I have time I'll try to fix the others. It can be a bit finnicky so no promises on when I'll be able to get around to it - but I'll try to always have at least one method working.

When it has no name it means it's hooked a function but can't find the name (i.e. offsets may have changed, or it's hooked the wrong function). Since it will download for each DLC, the latest one of the same name (in this case, blank) would overwrite any earlier ones - so if the name is broken it would only be able to be used for one DLC (but the decryptor also only looks for key and iv of the correct name, so you'd have to manually rename it even for that).  
In this case, method2 isn't hooking the right place so the key/iv is junk. I need to add in more error-checking at some point.
